### ISSUE TITLE
Issues with deprecated cobra variables

### ISSUE THREAD

**Issue by beenalad** [nvenayak/impact#51]
Relies on deprecated cobrapy variables for modeling, such as cobra Solution object attribute x_dict, which should be modified to 'fluxes'.
<img width="246" alt="Deprecated_variables_Solution" src="https://user-images.githubusercontent.com/52332466/84431832-d43ccd80-abe0-11ea-92f1-c66140982fe2.PNG">

**Comment by kraj593** [comment]
Resolved this by updating var names in commit https://github.com/nvenayak/impact/commit/cd1bbf0652daadd3d80fe696b4b06e014d37834e
